In [25]:
# map function is a good alternative for for loop

In [12]:
def print_result(i,k):
    return i*k

list(map(print_result, [2,3],[4,5]))

[8, 15]

In [13]:
import numpy as np

In [19]:
a = np.random.randn(20)
a

array([ 0.20753714,  0.55147568, -0.44161383,  0.74618976,  1.19932831,
        1.56457867,  1.04301788, -0.51689534,  0.45414051, -3.13954649,
        0.58416721,  0.02554697,  0.47068747, -0.60075522, -1.01821405,
        0.96893671,  0.71574332, -1.9535068 , -0.21345752, -0.17977282])

In [20]:
# split a into 5 array
b = np.split(a,5)
b

[array([ 0.20753714,  0.55147568, -0.44161383,  0.74618976]),
 array([ 1.19932831,  1.56457867,  1.04301788, -0.51689534]),
 array([ 0.45414051, -3.13954649,  0.58416721,  0.02554697]),
 array([ 0.47068747, -0.60075522, -1.01821405,  0.96893671]),
 array([ 0.71574332, -1.9535068 , -0.21345752, -0.17977282])]

In [21]:
b[0]

array([ 0.20753714,  0.55147568, -0.44161383,  0.74618976])

In [22]:
b[1]

array([ 1.19932831,  1.56457867,  1.04301788, -0.51689534])

In [23]:
b[2]

array([ 0.45414051, -3.13954649,  0.58416721,  0.02554697])

In [24]:
b[1:3]

[array([ 1.19932831,  1.56457867,  1.04301788, -0.51689534]),
 array([ 0.45414051, -3.13954649,  0.58416721,  0.02554697])]